---
- name: kafka
  hosts: all
  become: true
  remote_user: ubuntu
  tasks:
    - name: install default-jdk
      ansible.builtin.apt:
        name: default-jdk
        update_cache: true
        state: present
    -  name:  create a directory
       ansible.builtin.file:
          path: /usr/local/kafka
          state: directory
    -  name: Extract into opt directory
       ansible.builtin.unarchive:
         src: https://archive.apache.org/dist/kafka/3.2.0/kafka_2.13-3.2.0.tgz
         dest: /usr/local/kafka/
         remote_src: true
    -  name: Copy kafka docs
       ansible.builtin.copy:
         src: /usr/local/kafka/kafka_2.13-3.2.0/
         dest: /usr/local/kafka/
         remote_src: true
    - name: Touch the same file, but add/remove some permissions
      ansible.builtin.file:
        path: /etc/systemd/system/zookeeper.service
        state: touch
        mode: u+rw,g-wx,o-rwx
    - name: Touch the same file, but add/remove some permissions
      ansible.builtin.file:
        path: /etc/systemd/system/kafka.service
        state: touch
        mode: u+rw,g-wx,o-rwx
    - name: Insert/Update "Match User" configuration block in /etc/ssh/sshd_config
      ansible.builtin.blockinfile:
        path: /etc/systemd/system/zookeeper.service
        block: |
          [Unit]
          Description=Apache Zookeeper server
          Documentation=http://zookeeper.apache.org
          Requires=network.target remote-fs.target
          After=network.target remote-fs.target
          [Service]
          Type=simple
          ExecStart=/usr/local/kafka/bin/zookeeper-server-start.sh /usr/local/kafka/config/zookeeper.properties
          ExecStop=/usr/local/kafka/bin/zookeeper-server-stop.sh
          Restart=on-abnormal
          [Install]
          WantedBy=multi-user.target
    - name: Insert/Update "Match User" configuration block in /etc/ssh/sshd_config
      ansible.builtin.blockinfile:
        path: /etc/systemd/system/kafka.service
        block: |
          [Unit]
          Description=Apache Kafka Server
          Documentation=http://kafka.apache.org/documentation.html
          Requires=zookeeper.service
          [Service]
          Type=simple
          Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
          ExecStart=/usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties
          ExecStop=/usr/local/kafka/bin/kafka-server-stop.sh
          Restart=on-abnormal
          [Install]
          WantedBy=multi-user.target
    -  name: systemd manager configuration and enable kafka service
       ansible.builtin.systemd:
          daemon_reload: true
          name: zookeeper.service
          enabled: true
          state: restarted
    -  name: systemd manager configuration and enable kafka service
       ansible.builtin.systemd:
          daemon_reload: true
          name: kafka.service
          enabled: true
          state: restarted
    -  name: change directory using shell
       ansible.builtin.shell:
          chdir: /usr/local/kafka
          cmd: bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic testTopic